In [37]:
# test for CV function

import csv
import numpy as np
import re
import matplotlib.pyplot as plt


import pandas as pd
%matplotlib inline

regex1 = r"\d+"
regex2 = r"c\d+"
X = np.zeros((10000,1000)) #1.000x10.000 matrix

#load data
with open("../Exercise 1/data_train.csv") as csvfile:
    readCSV = csv.reader(csvfile,delimiter=',')
    next(readCSV) #discard header
    for row in readCSV:
        match = re.search(regex1,row[0])
        match2 = re.search(regex2,row[0])
        row_i = int(match.group(0))-1
        col_i = int(match2.group(0)[1:]) -1
        X[row_i,col_i] = int(row[1])
        


In [53]:
print 'X has ', np.count_nonzero(X), ' non-zeros.'

def cv(X, k=5):
    # split indices of nonz-zero values in k sets but randomly!
    nzR, nzC = np.nonzero(X)
    zipped = zip(nzR,nzC)
    np.random.shuffle(zipped)
    nzR, nzC = zip(*zipped)
    nzRsplit = np.array_split(nzR, k)
    nzCsplit = np.array_split(nzC, k)
     
    X_train_sets = []
    X_test_sets = []
    for i in range(k):
        X_train = np.copy(X)
        X_train[(nzRsplit[i], nzCsplit[i])] = 0
        print 'X_train has ', np.count_nonzero(X_train), ' non-zeros.'
        X_train_sets.append(X_train)
    
        X_test = np.zeros(X.shape)
        X_test[(nzRsplit[i], nzCsplit[i])] = X[(nzRsplit[i], nzCsplit[i])]
        print 'X_test has ', np.count_nonzero(X_test), ' non-zeros.'
        X_test_sets.append(X_test)
        
        
        

#testarr = np.array([[1,2,3], [0,5,6], [0,0,2]])
cv(X,5)

X has  1176952  non-zeros.
X_train has  941561  non-zeros.
X_test has  235391  non-zeros.
X_train has  941561  non-zeros.
X_test has  235391  non-zeros.
X_train has  941562  non-zeros.
X_test has  235390  non-zeros.
X_train has  941562  non-zeros.
X_test has  235390  non-zeros.
X_train has  941562  non-zeros.
X_test has  235390  non-zeros.


In [49]:
testarr = np.arange(12).reshape(3,4)
print testarr


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
